### ISSUE TITLE
Enhancement request : Create a connect/disconnect event so Zwave-JS-UI can log the connect/disconnect to consol on and show on consol

### ISSUE THREAD

**Issue by goldriver2** [zwave-js/zwave-js-server#1159]
I am converting some old Z-Net devices into Zwave-JS-UI embeded devices and I need a way to know if HomeAssistant is connected to the Z-WAVE-SERVER so I can change the status of the LED light on the Z-Net device depending on this connection. I actually have two state, red ==> Controler not ready, yellow ==> Driver ready and would like to have a green ligth when HA is connected to the Z-WAVE-SERVER. That could be used for any other zwave board with an RGB LED

Proposed solution: Create a connect/disconnect event so Zwave-JS-UI so ZWAVE-JS-UI is aware of the connect/disconnetc state

The actual alternative involves MQTT, Node-RED and a python script to grab the zwave device stats in HA, Quite a burden for just knowing a state of connection

**Comment by raman325** [comment]
you can accomplish this using the HA websocket API which you should be able to access from Node-RED. I don't know enough about Node-RED to know if it handles websocket subscriptions, but if it does, the 	`config_entries/subscribe` API might help you. The APIs you would need are registered here: https://github.com/home-assistant/core/blob/dev/homeassistant/components/config/config_entries.py

Your problem is outside the scope of the server so you won't be able to get any support for this problem here
