### ISSUE TITLE
Node values not correctly identified

### ISSUE THREAD

**Issue by mcozzo** [zwave-js/zwave-js-server#211]
-   [ ] a developer has told me to come here.

**Describe the bug**

The notification value metadata is missing the proper type (number) and states (Idle + monitoring)

Debug: https://pastebin.com/Cgs180A6
Debug: https://pastebin.com/6J5pVQMs
Debug: https://pastebin.com/1aEeS9C1 

States: Motion, tamper are provided to MQTT but do not show up in HomeAssistant. 

Device: http://www.getzooz.com/zooz-zse40-4-in-1-sensor.html
Node 23,24

Has never worked. 
zwavejs2mqtt: 4.0.0
zwave-js: 7.3.0

All instances are deployed through docker. 
  image: zwavejs/zwavejs2mqtt:latest
  image: homeassistant/home-assistant:stable

**To Reproduce**

1. Re-interview node
2. Restart / update Home Assistant
3. components are missing

**Comment by AlCalzone** [comment]
Transferring this here for further investigation. Driver-wise this seems to be fine.

**Comment by balloob** [comment]
@AlCalzone your explanation got me in the right direction I think. We would always update the value with the info that was in a value notification because we accidentally shared the underlying dictionary instead of making a copy.

With https://github.com/home-assistant-libs/zwave-js-server-python/pull/213 value notifications with invalid data should no longer update a value.

**Comment by kpine** [comment]
These values with missing metadata are not `"value notification"` events though, they are "`value updated"` events. Are there `"value notification"` events involved here? The pastebin debug logs have expired, so they are not accessible anymore. Who knows...

**Comment by MartinHjelmare** [comment]
If a `"value notification"` event taints the stored Value data all subsequent events for that Value can potentially be affected.

**Comment by AlCalzone** [comment]
In this particular case there should be a `"metadata updated"` and a `"value updated"` event, since these are statful notification variables.

**Comment by balloob** [comment]
Oh well maybe I caught an unrelated bug 🤣

**Comment by kpine** [comment]
The server [checks](https://github.com/zwave-js/zwave-js-server/blob/1595c0d76c1be6a5d73c747f2d99e078514d91bf/src/lib/forward.ts#L167) the `node.ready` flag and ignores any value/metadata events prior to the flag being true. That should prevent any incomplete values from being created within HA?

**Comment by balloob** [comment]
Good catch @kpine. We should add that check to `notification` and `firmware` events too.

**Comment by AlCalzone** [comment]
You are querying the metadata after the node is ready, right?

**Comment by balloob** [comment]
Yes. https://github.com/zwave-js/zwave-js-server/blob/1595c0d76c1be6a5d73c747f2d99e078514d91bf/src/lib/forward.ts#L116-L126

**Comment by raman325** [comment]
> Good catch @kpine. We should add that check to `notification` and `firmware` events too.

I added these in the linked PR but FYI notification and firmware events don't modify the state of the node in the library

**Comment by kpine** [comment]
The logs are now missing due to pastebin expiration, but was the original problem that the notification CC
values have the wrong metadata ("any")? If so, isn't it the same problem as https://github.com/home-assistant/core/issues/46982#issuecomment-831341082, which shows that even in zwavejs2mqtt the metadata is wrong (also https://github.com/home-assistant/core/issues/46982#issuecomment-830854696). If it's wrong in zwavejs2mqtt, then it means the server is not a problem.

**Comment by AlCalzone** [comment]
If you look at my comment above, the metadata seems to be correct. I can only imagine that the fallback metadata is being cached before the interview sets the correct metadata.

**Comment by raman325** [comment]
anyone know if this is still a problem?

**Comment by raman325** [comment]
@mcozzo apologies for the tag but just want to find out if you were able to resolve this issue. I will close it for now since you haven't responded in a while but happy to reopen if it's still a legitimate issue
