### ISSUE TITLE
no getValue (node.get_value)

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/zwave-js-server#466]
Hello,

I don't think we have crossed paths all that often - although I work on the Browser  and other areas of zwave-js.

I have been working with this, to expose zwave-js to another language (.Net).
todate - its going extremely! well, with a single DLL that contains an embedded instance of the server - its transparent.

I was in the middle of building out the methods, until I received

```json
{
  "type": "result",
  "success": false,
  "messageId": "29a3e1c7-0b69-4eeb-a7cf-4519a1c2e28a",
  "errorCode": "unknown_command",
  "args": {
    "command": "node.get_value"
  }
}
```

Now then, I see the values are dumped on the result of` start_listening` - so the developer who wishes to use .Net will need their own way to store values for later retrieval.  

But, are we open to expose this method? - my aim is to expose the various methods (well, the ones that matter) that the driver offers.

Hit me up on Slack if needs be.

**Comment by raman325** [comment]
The primary driver of architecture and feature priority for the server has been the Home Assistant integration, but the intent is to be able to control the driver over websockets, regardless of the client. That's a long way of saying yes, we are open to exposing this method!

Background in case you are curious: Our approach with the python library that's being used in the HA integration is to store the initial state dump internally on the client side and then to listen to events like value updates to update our internally stored state. Because of this, we haven't had a need for commands like `getValue`.

We are definitely not 100% in terms of the mapping between the driver APIs and the websocket APIs, so feel free to suggest/open PRs for any missing commands, especially if they would help with your integration. There may be some commands which can't follow the `zwave-js` API model entirely (e.g. for S2 inclusion, we had to split the single inclusion command into multiple commands and provide custom events so the client can pass and receive the right information), but we try to stay as close to the existing model as we can.

Feel free to open a PR for this command, or if you aren't ready to do that, I can put up a PR for that later today/tomorrow. Also I am on the `zwave-js` Slack as well (same username) so feel free to reach out there if you want to talk about the API/design

**Comment by marcus-j-davies** [comment]
Hi @raman325,

Thanks for the info.

> We are definitely not 100% in terms of the mapping between the driver APIs and the websocket APIs

To be fair, a large portion of the 'important stuff' is mapped already (upon a glance at least), but some of the basics aren't,
like setting a node name, location, getting a value back.

I don't yet know the code base here - So if I get to grips with it enough, I'll try and put up another PR (if not already done by you) - I already have one here to slightly improve the security.

> store the initial state dump internally

I guess this was the case. I think adding some of these utilities will provide quite big benefit, when its in use by other consumers.
