### ISSUE TITLE
What is the *-audit.json?

### ISSUE THREAD

**Issue by electrofloat** [zwave-js/zwave-js-server#542]
I'm running this server manually (meaning /home/zwavejs/zwave-js-server/node_modules/.bin/zwave-server /dev/tty0 --config /home/zwavejs/zwavejs-config.js") configured to log into a file.

I can see that a *-audit.log file is created in the directory where the actual log file is. In the json there are some "settings" it seems.
What are these? What are the possible values of them?

does keep, days=true, amount=7  means that it will create a new log file every day, and it will keep the last 7 of them?

Why is it so hard to find documentation about this?

**Comment by raman325** [comment]
The server doesn't do any logging to a file, just to console, so any files generated would be coming from the driver (node-zwave-js)

**Comment by electrofloat** [comment]
Up until a couple of hours ago I didn't even know that zwave-js-server exists.
Yesterday I read it somewhere that HA is planning to remove the zwave integration and I absolutely have to upgrade to the "new" zwavejs. I already knew about this zwavejs, but last I checked it was in a very "early access" state. Now I read the zwavejs integration page and saw that since I run the so called HA Core (it was not called that when I installed it back then) I only have the option to run the server myself. (no docker here).

Since there's no usable information on how to do in myself, I had to dig through google to get at least an idea about how to do it. That is when I came to a blog post saying that running the above command does the trick. So after much fiddling I was able to run it.

Now you are telling me that when I'm running zwave-server, I'm not running code from this repo, but I'm running something called node-zwave-js?
Also checked this whole project now and seeing: zwave-js-server, node-zwave-js , zwavejs2mqtt, log-transports, node-red-contrib-zwave-js, file-stream-rotator, ZWaveJS.NET, winston-daily-rotate-file , etc... what an absolute... what?

So should I ask the above question in the node-zwave-js repo then?

Also if I'm giving this option `--config /home/zwavejs/zwavejs-config.js` to `/home/zwavejs/zwave-js-server/node_modules/.bin/zwave-server` with content:
`
module.exports = {
  logConfig: {
    filename: "/home/zwavejs/log/zwave",
    forceConsole: false,
    logToFile: true,
    level: "info",
  },

  storage: {
    cacheDir: "/home/zwavejs/cache/data",
    deviceConfigPriorityDir: "/home/zwavejs/cache/data/config",
  },

  // Generated with: "< /dev/urandom tr -dc A-F0-9 | head -c32 ;echo"
  securityKeys: {
    S0_Legacy: Buffer.from("randomkey", "hex"),
  },
};
`
whose parameters am I setting here? zwavejs-server, or node-zwave-js?

thanks.

**Comment by raman325** [comment]
I'm a little confused by your tone that implies something was done to you... The zwave_js integration was introduced in January or February 2021. It's first release may have been considered early access, but at this point it is more feature complete than the `zwave` or `ozw` integrations. Those integrations have to be removed because they don't support Python 3.10. As for how the communication process works, see here: https://github.com/home-assistant/core/blob/dev/homeassistant/components/zwave_js/README.md `node-zwave-js` is the driver.

You are setting zwave-js driver parameters. The server is simply the mechanism by which HA talks to the driver.

Closing this as it's not relevant to this project.
